/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendarCard: typeof import('@nutui/nutui-taro')['CalendarCard']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
  }
}
